'use client';

import { Input } from '@shop/ui';
import { useTranslation } from '../../../../../lib/i18n-client';
import { ADMIN_PRODUCT_INPUT_CURRENCY, CURRENCIES } from '../../../../../lib/currency';
import { SHOW_COMPARE_AT_PRICE_FIELD } from '../constants/compareAtPriceVisibility.constants';
import { PRODUCT_FORM_FIELD, type ProductFormFieldId } from '../constants/productFormFieldIds.constants';
import { getProductFieldInputClassName } from '../utils/productFieldInputClassName';

interface SimpleProductFieldsProps {
  price: string;
  compareAtPrice: string;
  sku: string;
  quantity: string;
  invalidFieldId?: ProductFormFieldId | null;
  onPriceChange: (value: string) => void;
  onCompareAtPriceChange: (value: string) => void;
  onSkuChange: (value: string) => void;
  onQuantityChange: (value: string) => void;
}

export function SimpleProductFields({
  price,
  compareAtPrice,
  sku,
  quantity,
  invalidFieldId,
  onPriceChange,
  onCompareAtPriceChange,
  onSkuChange,
  onQuantityChange,
}: SimpleProductFieldsProps) {
  const { t } = useTranslation();

  return (
    <div>
      <h2 className="text-xl font-semibold text-gray-900 mb-4">{t('admin.products.add.productVariants')}</h2>
      <div className="bg-white border border-gray-200 rounded-lg p-6 space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              {t('admin.products.add.price')} *
            </label>
            <div className="flex items-center gap-2">
              <Input
                type="number"
                data-product-field={PRODUCT_FORM_FIELD.PRICE}
                value={price}
                onChange={(e) => onPriceChange(e.target.value)}
                placeholder={t('admin.products.add.pricePlaceholder')}
                className={getProductFieldInputClassName(
                  PRODUCT_FORM_FIELD.PRICE,
                  invalidFieldId,
                  'flex-1'
                )}
                min="0"
                step="0.01"
                aria-invalid={invalidFieldId === PRODUCT_FORM_FIELD.PRICE}
              />
              <span className="text-sm text-gray-500 whitespace-nowrap">{CURRENCIES[ADMIN_PRODUCT_INPUT_CURRENCY].symbol}</span>
            </div>
          </div>

          {SHOW_COMPARE_AT_PRICE_FIELD ? (
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                {t('admin.products.add.compareAtPrice')}
              </label>
              <div className="flex items-center gap-2">
                <Input
                  type="number"
                  value={compareAtPrice}
                  onChange={(e) => onCompareAtPriceChange(e.target.value)}
                  placeholder={t('admin.products.add.pricePlaceholder')}
                  className="flex-1"
                  min="0"
                  step="0.01"
                />
                <span className="text-sm text-gray-500 whitespace-nowrap">{CURRENCIES[ADMIN_PRODUCT_INPUT_CURRENCY].symbol}</span>
              </div>
            </div>
          ) : null}

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              {t('admin.products.add.sku')} *
            </label>
            <Input
              type="text"
              value={sku}
              onChange={(e) => onSkuChange(e.target.value)}
              placeholder={t('admin.products.add.autoGenerated')}
              className="w-full"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              {t('admin.products.add.quantity')} *
            </label>
            <Input
              type="number"
              data-product-field={PRODUCT_FORM_FIELD.QUANTITY}
              value={quantity}
              onChange={(e) => onQuantityChange(e.target.value)}
              placeholder={t('admin.products.add.quantityPlaceholder')}
              className={getProductFieldInputClassName(
                PRODUCT_FORM_FIELD.QUANTITY,
                invalidFieldId,
                'w-full'
              )}
              min="0"
              aria-invalid={invalidFieldId === PRODUCT_FORM_FIELD.QUANTITY}
            />
          </div>
        </div>
      </div>
    </div>
  );
}
